nohup: ignoring input
cuda available: False 
cuda available: False 
cuda available: False 
cuda available: False 
cuda available: False 
cuda available: False 
cuda available: False 
cuda available: False 
model initialized
training func is running after this line
Supervised Validation started
heuristic: one_step_greedy learning rate: 0.0001 epochs: 21 DataSet: UFSMDataset

/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/gcn/models_gcn.py:180: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  features = F.log_softmax(features.view(-1))
epochs 0 loss 0.00498094514196902 one_step_greedy_performance 2501.7302158273383 gcn_performance 13022.676258992806 random_performance 13871.611510791367
epochs 1 loss 0.010239788111997496 one_step_greedy_performance 2501.7302158273383 gcn_performance 3137.1942446043167 random_performance 13871.611510791367
Traceback (most recent call last):
  File "test_supervised_validation.py", line 153, in <module>
    t_plot, total_loss_val_np, val_ave_gcn_np, val_ave_mind_np, val_ave_rand_np = policy_sl.validation_epochs(epochs=args.epochs, lr=args.lr, val_dataset=val_dataset, dataset_type=dataset_type)
  File "/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/supervised/train_supervised_learning.py", line 798, in validation_epochs
    + '_epochs_' + str(epoch) + '_cuda.pth', map_location='cpu'))
  File "/home/x86_64-unknown-linux_ol7-gnu/anaconda-5.2.0/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './supervised/models/one_step_greedy/SmallErgTraining/layers7_test_lr0.0001/per_epochs/gcn_policy_one_step_greedy_pre_ErgDataset_epochs_2_cuda.pth'
